[workflows:tests] remove Python 3.5
currently causing errors in the setup phase:

  Error: Could not find a version that satisfies the requirement pip
  Error: No matching distribution found for pip
  Error: The process '/usr/bin/bash' failed with exit code 1